export const ROUTES = {
  home: "/",
  properties: "/propiedades",
  rentals: "/alquileres",
  propertyDetail: "/propiedades/:slug",
  contact: "/contacto",
  adminLogin: "/admin/login",
  adminRoot: "/admin",
  adminDashboard: "/admin",
  adminHero: "/admin/hero",
  adminClients: "/admin/clientes",
  adminClientNew: "/admin/clientes/nuevo",
  adminClientEdit: "/admin/clientes/:id/editar",
  adminCalendar: "/admin/calendario",
  adminSales: "/admin/ventas",
  adminSaleNew: "/admin/ventas/nueva",
  adminSaleEdit: "/admin/ventas/:id/editar",
  adminProperties: "/admin/propiedades",
  adminPropertyNew: "/admin/propiedades/nueva",
  adminPropertyEdit: "/admin/propiedades/:slug/editar",
  adminTestimonials: "/admin/testimonios",
};
