export const ROUTES = {
  home: "/",
  properties: "/propiedades",
  rentals: "/alquileres",
  propertyDetail: "/propiedades/:slug",
  contact: "/contacto",
  adminLogin: "/admin/login",
  adminRoot: "/admin",
  adminDashboard: "/admin",
  adminHero: "/admin/hero",
  adminProperties: "/admin/propiedades",
  adminPropertyNew: "/admin/propiedades/nueva",
  adminPropertyEdit: "/admin/propiedades/:slug/editar",
  adminTestimonials: "/admin/testimonios",
};
