export const PROPERTY_STATUS = ["disponible", "vendido", "alquilado", "reservado"];
export const OPERATION_TYPES = ["venta", "alquiler", "venta_o_alquiler"];

export const emptyProperty = {
  id: "",
  titulo: "",
  slug: "",
  tipoOperacion: "venta",
  tipoPropiedad: "",
  precio: 0,
  consultarPrecio: false,
  moneda: "USD",
  ubicacion: "",
  googleMapsUrl: "",
  superficie: 0,
  dormitorios: 0,
  banos: 0,
  cochera: 0,
  caracteristicasExtras: [],
  descripcionCorta: "",
  descripcionLarga: "",
  estado: "disponible",
  imagenPrincipal: "",
  imagenes: [],
  destacadaEnPortada: false,
  publicada: true,
  lotOverlay: {
    enabled: false,
    imageUrl: "",
    points: [],
    closed: false,
    strokeColor: "#7DD3FC",
    strokeWidth: 0.75,
    fillColor: "#50BEFF",
    fillOpacity: 0.18,
    animationDuration: 1.35,
    animate: true,
    animateOnView: true,
    animateOnce: true,
    showLabel: true,
    labelTitle: "",
    labelSubtitle: "",
  },
  createdAt: new Date().toISOString(),
};
