export const PROPERTY_STATUS = ["disponible", "vendido", "alquilado", "reservado"];
export const OPERATION_TYPES = ["venta", "alquiler", "venta_o_alquiler"];

export const emptyProperty = {
  id: "",
  titulo: "",
  slug: "",
  tipoOperacion: "venta",
  tipoPropiedad: "",
  precio: 0,
  consultarPrecio: false,
  moneda: "USD",
  ubicacion: "",
  googleMapsUrl: "",
  superficie: 0,
  dormitorios: 0,
  banos: 0,
  cochera: 0,
  caracteristicasExtras: [],
  descripcionCorta: "",
  descripcionLarga: "",
  estado: "disponible",
  imagenPrincipal: "",
  imagenes: [],
  destacadaEnPortada: false,
  publicada: true,
  loteDelimitacion: {
    imageUrl: "",
    points: [],
    closed: false,
    label: "",
    showLabel: true,
  },
  createdAt: new Date().toISOString(),
};
