export const PROPERTY_STATUS = ["disponible", "vendido", "alquilado", "reservado"];
export const OPERATION_TYPES = ["venta", "alquiler", "venta_o_alquiler"];

export const emptyProperty = {
  id: "",
  titulo: "",
  slug: "",
  tipoOperacion: "venta",
  tipoPropiedad: "",
  precio: 0,
  consultarPrecio: false,
  moneda: "USD",
  ubicacion: "",
  googleMapsUrl: "",
  superficie: 0,
  dormitorios: 0,
  banos: 0,
  cochera: 0,
  caracteristicasExtras: [],
  descripcionCorta: "",
  descripcionLarga: "",
  estado: "disponible",
  imagenPrincipal: "",
  imagenes: [],
  destacadaEnPortada: false,
  publicada: true,
  lotOverlay: {
    imageUrl: "",
    previewUrl: "",
    points: [],
    closed: false,
    strokeColor: "#2B6D92",
    strokeWidth: 1.8,
    fillColor: "#2B6D92",
    fillOpacity: 0.18,
    animationDuration: 1.8,
    animate: true,
    animateOnView: true,
    animateOnce: true,
    showLabel: true,
    label: {
      name: "",
      surface: "",
    },
  },
  createdAt: new Date().toISOString(),
};
